version: "3.5"

services:
  db:
    image: postgres:16.0
    container_name: devjobs-db
    stdin_open: true
    tty: true
    restart: always
    environment:
      # POSTGRES_PASSWORD: example
      # - POSTGRES_DB=movies
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      # - pgdata:/data/db
      - postgres_data:/var/lib/postgresql/data/
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devjobs-client
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  # pgdata:
  postgres_data:
